// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brkzsfbiuazrbmpnpzyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJya3pzZmJpdWF6cmJtcG5wenlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Njg3MTYsImV4cCI6MjA2ODM0NDcxNn0.5F4wv_bhgY_HCwxOdGSxbmcXKiem3VEY0PQG3n6U_nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});